######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 7 15:01:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += filewatcher.h
SOURCES += filewatcher.cpp main.cpp
